### ISSUE TITLE
help wanted : Create Machine Learning content/projects

### ISSUE THREAD

**Issue by sakethramanujam** [GVP-AI-Club/Hacktober-at-GVP#4]
I want people looking into this issue to be doing any one of the following:
- Create some cool basic machine learning projects for others to work on.
- Create machine learning content using which people can look into and learn.
- Basically, teach people code!

Look into [CONTRIBUTIONS.md](https://github.com/GVP-AI-Club/Hacktober-at-GVP/blob/master/CONTRIBUTIONS.md) for further details.

**Comment by adityasingh69** [comment]
What exactly do you want

**Comment by sakethramanujam** [comment]
> What exactly do you want
@adityasingh69 
Anything starting from algorithms in python to notebooks that explain some pre-solved problems.
